"""
Django settings for sec project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# /code
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# /code
NEW_BASE_DIR = os.path.abspath(os.path.join(BASE_DIR))

# The absolute path to the directory where collectstatic will collect
# static files for deployment.
STATIC_ROOT = os.path.join(NEW_BASE_DIR, 'static_r')

# The file storage engine to use when collecting static files with the
# collectstatic management command.
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_wb%*y)=g!c+ci3*13+k4p&#t!+!^r8x1fb$fly-%#yi_63l(^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_extensions',
    'crispy_forms',
    'accounts',
    'sec',
    'dashboard',
    'webpack_loader',
    'company',
    'team_member',
    'django_tables2'
]

# webpack loader
# django-webpack-loader
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sec.urls'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# custom template and project path
SETTINGS_DIR = os.path.dirname(__file__)
PROJECT_PATH = os.path.join(SETTINGS_DIR, os.pardir)
PROJECT_PATH = os.path.abspath(PROJECT_PATH)

ROOT_PROJECT_NAME = ''

# master template path
TEMPLATE_PATH = os.path.join(NEW_BASE_DIR, ROOT_PROJECT_NAME, 'templates',)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            TEMPLATE_PATH,
            os.path.join(os.path.join(PROJECT_PATH, 'accounts',), 'templates'),
            os.path.join(os.path.join(PROJECT_PATH, 'dashboard',), 'templates', 'dashboard'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# authentication setting
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

WSGI_APPLICATION = 'sec.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'task_management',
        'USER': 'root',
        'PASSWORD': 'abc',
        'HOST': 'db',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# This setting defines the additional locations the staticfiles app
# will traverse if the FileSystemFinder finder is enabled
STATICFILES_DIRS = [
    os.path.join(NEW_BASE_DIR, 'static'),
]

# The list of finder backends that know how to find static files
# in various locations.
STATICFILES_FINDERS = [
    # The default will find files stored in the STATICFILES_DIRS setting
    'django.contrib.staticfiles.finders.FileSystemFinder',
    # static subdirectory of each app
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# allauth settings
# https://django-allauth.readthedocs.io/en/latest/configuration.html
SITE_ID = 1  # for allauth
LOGIN_REDIRECT_URL = '/' #django settings
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_MAX_LENGTH = 191
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/'

SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_QUERY_EMAIL = True

# other allauth setting
ACCOUNT_ADAPTER = 'accounts.adapter.AccountAdapter'  # for allauth

# allauth logout on get
ACCOUNT_LOGOUT_ON_GET = False  # for allauth (Allauth no more supporting logout on get)

# customize login and signup form, allauth
ACCOUNT_FORMS = {
    'login': 'accounts.forms.OverrideLoginForm',
}
