version: '2'
services:
  web:
    build:
      context: ..
      dockerfile: './docker/Dockerfile-web'
    volumes:
      - '..:/code'
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - STATIC_ROOT=${STATIC_ROOT}
    links:
      - db
    command: 'python manage.py runserver_plus 0.0.0.0:8000'
    ports:
      - '${DJANGO_PORT}:8000'

  db:
    image: 'mariadb:10.3'
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=abc
      - MYSQL_DATABASE=task_db

volumes:
  db_data:
    driver: 'local'
