# Generated by Django 2.1.5 on 2020-03-03 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='id',
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='team_member', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
