# Generated by Django 2.1.5 on 2020-04-20 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0002_auto_20200303_0926'),
        ('task', '0002_auto_20200309_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('activity_type', models.SmallIntegerField(choices=[('Add Comment', 1), ('Add Attachment', 2), ('Change status', 3)], help_text='Type of activity')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team_member.TeamMember'),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='task.Task'),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='team_member.TeamMember'),
        ),
    ]
