# Generated by Django 2.1.5 on 2020-04-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20200421_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivityStatus',
            fields=[
                ('task_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task_activity_status', serialize=False, to='task.TaskActivity')),
                ('status_before', models.SmallIntegerField(choices=[(1, 'New'), (2, 'In progress'), (3, 'Pending'), (4, 'Completed')], db_index=True)),
                ('status_after', models.SmallIntegerField(choices=[(1, 'New'), (2, 'In progress'), (3, 'Pending'), (4, 'Completed')], db_index=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
