# Generated by Django 2.1.5 on 2020-03-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
            ],
        ),
    ]
