
ADD_COMMENT = 'Add Comment'
ADD_ATTACHMENT = 'Add Attachment'
CHANGE_STATUS = 'Change status'

ADD_COMMENT_INT = 1
ADD_ATTACHMENT_INT = 2
CHANGE_STATUS_INT = 3

ACTIVITY = [
    ADD_COMMENT,
    ADD_ATTACHMENT,
    CHANGE_STATUS
]

ACTIVITY_INT = [
    ADD_COMMENT_INT,
    ADD_ATTACHMENT_INT,
    CHANGE_STATUS_INT
]

ACTIVITY_OPTION = tuple(zip(ACTIVITY_INT, ACTIVITY))
