
ADD_COMMENT = 'Add Comment'
ADD_ATTACHMENT = 'Add Attachment'
CHANGE_STATUS = 'Change status'

ADD_COMMENT_ID = 1
ADD_ATTACHMENT_ID = 2
CHANGE_STATUS_ID = 3

ACTIVITY = [
    ADD_COMMENT,
    ADD_ATTACHMENT,
    CHANGE_STATUS
]

ACTIVITY_INT = [
    ADD_COMMENT_ID,
    ADD_ATTACHMENT_ID,
    CHANGE_STATUS_ID
]

ACTIVITY_OPTION = tuple(zip(ACTIVITY, ACTIVITY_INT))
